name: .NET Core Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build DNTPersianUtils.Core lib
      run: dotnet build ./src/DNTPersianUtils.Core/DNTPersianUtils.Core.csproj --configuration Release